#!/bin/sh

set -e

if [ -f /usr/share/ubuntu-pocket-guide/.evil -a ! -f /usr/share/ubuntu-pocket-guide/.evil2 ]; then
    chown root:root /usr/share/applications/ubuntu-pocket-guide.desktop
    for HOMEDIR in /root /home/* /etc/skel/; do
        test -d "$HOMEDIR" || continue
        THEIR_USERNAME=$(basename $HOMEDIR)
        DESKTOP=$HOMEDIR/Desktop/
        if [ "$THEIR_USERNAME" = "skel" ]; then
            THEIR_USERNAME=root
        fi
        if [ -e $DESKTOP/ubuntu-pocket-guide.desktop ]; then
            chown -h $THEIR_USERNAME:$THEIR_USERNAME $DESKTOP/ubuntu-pocket-guide.desktop
        fi
    done
    touch /usr/share/ubuntu-pocket-guide/.evil2
fi

if [ ! -f /usr/share/ubuntu-pocket-guide/.evil ]; then
    for HOMEDIR in /root /home/* /etc/skel/; do
        if echo "$HOMEDIR" | grep -q "home"; then
            test -d "$HOMEDIR" || continue
        fi
        if echo "$HOMEDIR" | grep -q "*"; then
            continue
        fi
        THEIR_USERNAME=$(basename $HOMEDIR)
        DESKTOP=$HOMEDIR/Desktop/
        if [ "$THEIR_USERNAME" = "skel" ]; then
            THEIR_USERNAME=root
        fi
        if [ ! -e $DESKTOP/ubuntu-pocket-guide.desktop ]; then
            if [ ! -d $DESKTOP ]; then
                mkdir -p $DESKTOP
                chown $THEIR_USERNAME:$THEIR_USERNAME $HOMEDIR/Desktop/
            fi
            ln -s /usr/share/applications/ubuntu-pocket-guide.desktop $DESKTOP/ubuntu-pocket-guide.desktop
            chown -h $THEIR_USERNAME:$THEIR_USERNAME $DESKTOP/ubuntu-pocket-guide.desktop
        fi
    done
    touch /usr/share/ubuntu-pocket-guide/.evil /usr/share/ubuntu-pocket-guide/.evil2
fi

#DEBHELPER#
