#!/bin/sh

set -e

if [ -f /usr/share/ubuntu-pocket-guide/.evil -a "$1" = "remove" ]; then
    for HOMEDIR in /root /home/* /etc/skel/; do
        test -d "$HOMEDIR" || continue
        if echo "$HOMEDIR" | grep -q "*"; then
            continue
        fi
        DESKTOP=$HOMEDIR/Desktop/
        if [ -h $DESKTOP/ubuntu-pocket-guide.desktop -a "$(readlink -f $DESKTOP/ubuntu-pocket-guide.desktop)" = "/usr/share/applications/ubuntu-pocket-guide.desktop" ]; then
            rm -f $DESKTOP/ubuntu-pocket-guide.desktop
        fi
    done
    rm -f /usr/share/ubuntu-pocket-guide/.evil /usr/share/ubuntu-pocket-guide/.evil2
    if [ -z "$(ls -A /usr/share/ubuntu-pocket-guide/)" ]; then
        rmdir /usr/share/ubuntu-pocket-guide/
    fi
fi

#DEBHELPER#
